config/routes.rb
Rails.application.routes.draw do
  #get 'home/index'
  resources :consulta
  resources :medicos do
    resources only: [:ListagemConsultas]
    get 'listagem' => 'consulta#ListagemConsultas'
  end
  resources :pacientes

  root to: "home#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/controllers/consulta_controller.rb
class ConsultaController < ApplicationController
  before_action :set_consultum, only: %i[ show edit update destroy ]

  # GET /consulta or /consulta.json
  def index
    @consulta = Consultum.all
  end

  def ListagemConsultas
    @consultas = Consultum.where(medico_id: params[:medico_id])
  end

  # GET /consulta/1 or /consulta/1.json
  def show
  end

  # GET /consulta/new
  def new
    @consultum = Consultum.new
  end

  # GET /consulta/1/edit
  def edit
  end

  # POST /consulta or /consulta.json
  def create
    @medico = Medico.find(consultum_params[:medico_id])
    @paciente = Paciente.find(consultum_params[:paciente_id])
    @consultum = Consultum.new(consultum_params)
    @medico.consultums << @consultum
    @paciente.consultums << @consultum

    respond_to do |format|
      if @consultum.save
        format.html { redirect_to consultum_url(@consultum), notice: "Consultum was successfully created." }
        format.json { render :show, status: :created, location: @consultum }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @consultum.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /consulta/1 or /consulta/1.json
  def update
    respond_to do |format|
      if @consultum.update(consultum_params)
        format.html { redirect_to consultum_url(@consultum), notice: "Consultum was successfully updated." }
        format.json { render :show, status: :ok, location: @consultum }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @consultum.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /consulta/1 or /consulta/1.json
  def destroy
    @consultum.destroy

    respond_to do |format|
      format.html { redirect_to consulta_url, notice: "Consultum was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_consultum
      @consultum = Consultum.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def consultum_params
      params.require(:consultum).permit(:data, :horario, :paciente_id, :medico_id)
    end
end

app/helpers/consulta_helper.rb
module ConsultaHelper
end

app/views/consulta/ListagemConsultas.erb
<p style="color: green"><%= notice %></p>

<h1>Consultas Agendadas</h1>

<div id="consulta">
  <% @consultas.each do |consultum| %>
    <%= render consultum %>
    <p>
      <%= link_to "Show this consultum", consultum %>
    </p>
  <% end %>
</div>

<br>
<br>
<br>
<br>
<br>
<%= link_to "Voltar para Home" , root_path%>

app/views/consulta/_consultum.html.erb
<div id="<%= dom_id consultum %>">
  <p>
    <strong>Data:</strong>
    <%= consultum.data %>
  </p>

  <p>
    <strong>Horario:</strong>
    <%= consultum.horario %>
  </p>

  <p>
    <strong>Paciente:</strong>
    <%= Paciente.find(consultum.paciente_id).nome %>
  </p>

  <p>
    <strong>Medico:</strong>
    <%= Medico.find(consultum.medico_id).nome %>
  </p>

</div>

app/views/consulta/_form.html.erb
<%= form_with(model: consultum) do |form| %>
  <% if consultum.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(consultum.errors.count, "error") %> prohibited this consultum from being saved:</h2>

      <ul>
        <% consultum.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :data, style: "display: block" %>
    <%= form.date_field :data %>
  </div>

  <div>
    <%= form.label :horario, style: "display: block" %>
    <%= form.select(:horario, %w[00:00 01:00 02:00 03:00 04:00 05:00 06:00 07:00 08:00 09:00 10:00
    11:00 12:00 13:00 14:00 15:00 16:00 17:00 18:00 19:00 20:00 21:00 22:00 23:00])%>
  </div>

  <div>
    <%= form.label :paciente_id, style: "display: block" %>
    <%= form.collection_select(:paciente_id, Paciente.all, :id, :nome, prompt:true)%>
  </div>

  <div>
    <%= form.label :medico_id, style: "display: block" %>
    <%= form.collection_select(:medico_id, Medico.all, :id, :nome, prompt:true)%>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/consulta/edit.html.erb
<h1>Editing consultum</h1>

<%= render "form", consultum: @consultum %>

<br>

<div>
  <%= link_to "Show this consultum", @consultum %> |
  <%= link_to "Back to consulta", consulta_path %>
</div>

app/views/consulta/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Consulta</h1>

<div id="consulta">
  <% @consulta.each do |consultum| %>
    <%= render consultum %>
    <p>
      <%= link_to "Show this consultum", consultum %>
    </p>
  <% end %>
</div>

<%= link_to "New consultum", new_consultum_path %>
<br>
<br>
<br>
<br>
<br>
<%= link_to "Voltar para Home" , root_path%>

app/views/consulta/new.html.erb
<h1>New consultum</h1>

<%= render "form", consultum: @consultum %>

<br>

<div>
  <%= link_to "Back to consulta", consulta_path %>
</div>

app/views/consulta/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @consultum %>

<div>
  <%= link_to "Edit this consultum", edit_consultum_path(@consultum) %> |
  <%= link_to "Back to consulta", consulta_path %>

  <%= button_to "Destroy this consultum", @consultum, method: :delete %>
</div>